# Generated by Django 2.2 on 2019-06-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='uemail',
            field=models.CharField(max_length=40, verbose_name='邮箱'),
        ),
    ]
