# Generated by Django 2.2 on 2019-06-18 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='total_price',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='orderinfo',
            old_name='transit_price',
            new_name='transit_amount',
        ),
    ]
