# Generated by Django 2.2 on 2019-06-13 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='indexpromotionbanner',
            table='indexPromotion',
        ),
        migrations.AlterModelTable(
            name='indextypegoodsbanner',
            table='indexTypeGoods',
        ),
    ]
